export const Data = [
]

export const SALES_DATA = [
    {
        ID: '1',
        ENTERPRISE: 'Enterprise 1',
        TYPE: 'Type 1',
        ADDRESS: 'Address 1',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 1',
        EMAIL: 'Email 1',
        WEBSITE: 'Website 1',
        KGST: 'KGST 1',
        TIN: 'TIN 1',
        CST: 'CST 1',
    },
    {
        ID: '2',
        ENTERPRISE: 'Enterprise 2',
        TYPE: 'Type 2',
        ADDRESS: 'Address 2',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 2',
        EMAIL: 'Email 2',
        WEBSITE: 'Website 2',
        KGST: 'KGST 2',
        TIN: 'TIN 2',
        CST: 'CST 2',
    },
    {
        ID: '3',
        ENTERPRISE: 'Enterprise 3',
        TYPE: 'Type 3',
        ADDRESS: 'Address 3',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 3',
        EMAIL: 'Email 3',
        WEBSITE: 'Website 3',
        KGST: 'KGST 3',
        TIN: 'TIN 3',
        CST: 'CST 3',
    },
    {
        ID: '4',
        ENTERPRISE: 'Enterprise 4',
        TYPE: 'Type 4',
        ADDRESS: 'Address 4',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 4',
        EMAIL: 'Email 4',
        WEBSITE: 'Website 4',
        KGST: 'KGST 4',
        TIN: 'TIN 4',
        CST: 'CST 4',
    },
    {
        ID: '5',
        ENTERPRISE: 'Enterprise 5',
        TYPE: 'Type 5',
        ADDRESS: 'Address 5',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 5',
        EMAIL: 'Email 5',
        WEBSITE: 'Website 5',
        KGST: 'KGST 5',
        TIN: 'TIN 5',
        CST: 'CST 5',
    },
]

export const PURCHASES_DATA = [
    {
        ID: '1',
        ENTERPRISE: 'Enterprise 1',
        TYPE: 'Type 1',
        ADDRESS: 'Address 1',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 'Phone Number 1',
        FAX: 'Fax 1',
        EMAIL: 'Email 1',
        WEBSITE: 'Website 1',
        KGST: 'KGST 1',
        TIN: 'TIN 1',
        CST: 'CST 1',
    },
    {
        ID: '2',
        ENTERPRISE: 'Enterprise 2',
        TYPE: 'Type 2',
        ADDRESS: 'Address 2',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543201,
        FAX: 'Fax 2',
        EMAIL: 'Email 2',
        WEBSITE: 'Website 2',
        KGST: 'KGST 2',
        TIN: 'TIN 2',
        CST: 'CST 2',
    },
    {
        ID: '3',
        ENTERPRISE: 'Enterprise 3',
        TYPE: 'Type 3',
        ADDRESS: 'Address 3',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543201,
        FAX: 'Fax 3',
        EMAIL: 'Email 3',
        WEBSITE: 'Website 3',
        KGST: 'KGST 3',
        TIN: 'TIN 3',
        CST: 'CST 3',
    },
    {
        ID: '4',
        ENTERPRISE: 'Enterprise 4',
        TYPE: 'Type 4',
        ADDRESS: 'Address 4',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543201,
        FAX: 'Fax 4',
        EMAIL: 'Email 4',
        WEBSITE: 'Website 4',
        KGST: 'KGST 4',
        TIN: 'TIN 4',
        CST: 'CST 4',
    },
    {
        ID: '5',
        ENTERPRISE: 'Enterprise 5',
        TYPE: 'Type 5',
        ADDRESS: 'Address 5',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543201,
        FAX: 'Fax 5',
        EMAIL: 'Email 5',
        WEBSITE: 'Website 5',
        KGST: 'KGST 5',
        TIN: 'TIN 5',
        CST: 'CST 5',
    },
    {
        ID: '6',
        ENTERPRISE: 'Enterprise 6',
        TYPE: 'Type 6',
        ADDRESS: 'Address 6',
        CARD_NUMBER: 123456781234,
        PHONE_NUMBER: 9876543201,
        FAX: 'Fax 6',
        EMAIL: 'Email 6',
        WEBSITE: 'Website 6',
        KGST: 'KGST 6',
        TIN: 'TIN 6',
        CST: 'CST 6',
    }
]

export const ITEMS_DATA = [
    {
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        PRICE: 'Price 1',
    },
    {
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        PRICE: 'Price 2',
    },
    {
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        PRICE: 'Price 3',
    },
    {
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        PRICE: 'Price 4',
    },
    {
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        PRICE: 'Price 5',
    },
    {
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        PRICE: 'Price 6',
    }
]

export const SALES = [{
    ID: 'SALE 1',
    DATE: new Date('10/12/2021'),
    ENTERPRISE: 'Enterprise 1',
    ITEM: 'Item 1',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
},
{
    ID: 'SALE 2',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 2',
    ITEM: 'Item 2',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
},
{
    ID: 'SALE 3',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 3',
    ITEM: 'Item 3',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
},
{
    ID: 'SALE 4',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 4',
    ITEM: 'Item 4',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
},
{
    ID: 'SALE 5',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 5',
    ITEM: 'Item 5',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
},
{
    ID: 'SALE 6',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 6',
    ITEM: 'Item 6',
    QUANTITY: 5,
    PRICE: 1599,
    DISCOUNT: 0,
    TOTAL: 1599,
    PAID: 1599,
    BALANCE: 0,
}]

export const PURCHASES = [{
    ID: 'PURCHASE 1',
    DATE: new Date('06/04/2024'),
    ENTERPRISE: 'Enterprise 1',
    ITEM: 'Item 1',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
},
{
    ID: 'PURCHASE 2',
    DATE: new Date('06/06/2024'),
    ENTERPRISE: 'Enterprise 2',
    ITEM: 'Item 2',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
},
{
    ID: 'PURCHASE 3',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 3',
    ITEM: 'Item 3',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
},
{
    ID: 'PURCHASE 4',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 4',
    ITEM: 'Item 4',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
},
{
    ID: 'PURCHASE 5',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 5',
    ITEM: 'Item 5',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
},
{
    ID: 'PURCHASE 6',
    DATE: new Date('12/12/2021'),
    ENTERPRISE: 'Enterprise 6',
    ITEM: 'Item 6',
    QUANTITY: 5,
    PRICE: 1499,
    DISCOUNT: 0,
    TOTAL: 1499,
    CREDIT: 0,
    DEBIT: 1499,
    BALANCE: 0,
}
]

export const PERIODIC_PURCHASE = [
    {
        ID: 'PURCHASE 1',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    },
    {
        ID: 'PURCHASE 2',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    },
    {
        ID: 'PURCHASE 3',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    },
    {
        ID: 'PURCHASE 4',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    },
    {
        ID: 'PURCHASE 5',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    },
    {
        ID: 'PURCHASE 6',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        PRICE: 1499,
        DISCOUNT: 0,
        TOTAL: 1499,
        CREDIT: 0,
        DEBIT: 1499,
        BALANCE: 0,
    }
]

export const PERIODIC_SALES = [
    {
        ID: 'SALE 1',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'SALE 2',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'SALE 3',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'SALE 4',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'SALE 5',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'SALE 6',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    }
]

export const ALL_STOCK = [
    {
        ID: 'All Stock 1',
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    },
    {
        ID: 'All Stock 2',
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    },
    {
        ID: 'All Stock 3',
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    },
    {
        ID: 'All Stock 4',
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    },
    {
        ID: 'All Stock 5',
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    },
    {
        ID: 'All Stock 6',
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        EDIT: 'EDIT',
    }
]

export const IN_STOCK = [
    {
        ID: 'In Stock 1',
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'In Stock 2',
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'In Stock 3',
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'In Stock 4',
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'In Stock 5',
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'In Stock 6',
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    }
]

export const RETURN = [
    {
        ID: 'Return 1',
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'Return 2',
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'Return 3',
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'Return 4',
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'Return 5',
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    },
    {
        ID: 'Return 6',
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
    }
]

export const DETAILS = [
    {
        ID: 'Details 1',
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',
    },
    {
        ID: 'Details 2',
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',
    },
    {
        ID: 'Details 3',
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',
    },
    {
        ID: 'Details 4',
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',
    },
    {
        ID: 'Details 5',
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',
    },
    {
        ID: 'Details 6',
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        SIZE: 'S, M, L, XL',
        PRICE: 1599,
        ALLSTOCK: 5,
        INSTOCK: 5,
        RETURN: 0,
        EDIT: 'EDIT',

    }
]


export const BILLING_DATA = [
    {
        ID: 'Billing 1',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 1',
        ITEM: 'Item 1',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'Billing 2',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 2',
        ITEM: 'Item 2',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'Billing 3',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 3',
        ITEM: 'Item 3',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'Billing 4',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 4',
        ITEM: 'Item 4',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'Billing 5',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 5',
        ITEM: 'Item 5',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    },
    {
        ID: 'Billing 6',
        DATE: new Date('12/12/2021'),
        ENTERPRISE: 'Enterprise 6',
        ITEM: 'Item 6',
        QUANTITY: 5,
        PRICE: 1599,
        DISCOUNT: 0,
        TOTAL: 1599,
        PAID: 1599,
        BALANCE: 0,
    }
]

export const MARKET_DATA = [
    {
        ID: 'Market 1',
        ENTERPRISE: 'Enterprise 1',
        ADDRESS: 'Address 1',
        LOCATION: 'Location 1',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 1',
        EMAIL: 'Email 1',
        WEBSITE: 'Website 1',
        KGST: 'KGST 1',
        TIN: 'TIN 1',
        CST: 'CST 1',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    },
    {
        ID: 'Market 2',
        ENTERPRISE: 'Enterprise 2',
        ADDRESS: 'Address 2',
        LOCATION: 'Location 2',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 2',
        EMAIL: 'Email 2',
        WEBSITE: 'Website 2',
        KGST: 'KGST 2',
        TIN: 'TIN 2',
        CST: 'CST 2',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    },
    {
        ID: 'Market 3',
        ENTERPRISE: 'Enterprise 3',
        ADDRESS: 'Address 3',
        LOCATION: 'Location 3',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 3',
        EMAIL: 'Email 3',
        WEBSITE: 'Website 3',
        KGST: 'KGST 3',
        TIN: 'TIN 3',
        CST: 'CST 3',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    },
    {
        ID: 'Market 4',
        ENTERPRISE: 'Enterprise 4',
        ADDRESS: 'Address 4',
        LOCATION: 'Location 4',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 4',
        EMAIL: 'Email 4',
        WEBSITE: 'Website 4',
        KGST: 'KGST 4',
        TIN: 'TIN 4',
        CST: 'CST 4',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    },
    {
        ID: 'Market 5',
        ENTERPRISE: 'Enterprise 5',
        ADDRESS: 'Address 5',
        LOCATION: 'Location 5',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        PHONE_NUMBER: 9876543211,
        FAX: 'Fax 5',
        EMAIL: 'Email 5',
        WEBSITE: 'Website 5',
        KGST: 'KGST 5',
        TIN: 'TIN 5',
        CST: 'CST 5',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    },
    {
        ID: 'Market 6',
        ENTERPRISE: 'Enterprise 6',
        ADDRESS: 'Address 6',
        LOCATION: 'Location 6',
        CARD_NUMBER: 123456781234,
        CONTACT: 9876543211,
        EMAIL: 'Email 6',
        WEBSITE: 'Website 6',
        KGST: 'KGST 6',
        TIN: 'TIN 6',
        CST: 'CST 6',
        EDIT: 'EDIT',
        DELETE: 'DELETE',
    }
]

// export const ALL_STOCK_ITEMS_DATA = [
//     {
//         ID: 'ASID 1',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 1',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     },
//     {
//         ID: 'ASID 2',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 2',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     },
//     {
//         ID: 'ASID 3',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 3',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     },
//     {
//         ID: 'ASID 4',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 4',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     },
//     {
//         ID: 'ASID 5',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 5',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     },
//     {
//         ID: 'ASID 6',
//         ENTERPRISE: 'Enterprise 1',
//         ITEM: 'Item 6',
//         QUANTITY: 5,
//         SIZE: 'S, M, L, XL',
//         PRICE: 1599,
//     }
// ]

export const DATABASE = [
    {
        ID: 'Database 1',
        ALL_STOCK: [
            {
                ID: 'ASID 1',
                ENTERPRISE: 'Enterprise 1',
                ITEMS: [
                    {
                        ID: 'Item 1',
                        ITEM: 'Item 1',
                        QUANTITY: 5,
                        IS_STOCK_AVAILABLE: true,
                        TOTAL_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 10,
                            S: 10,
                            M: 20,
                            L: 10,
                            XL: 10,
                            XXL: 10,
                            XXXL: 10,
                        },
                        IN_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 2,
                            L: 0,
                            XL: 1,
                            XXL: 0,
                            XXXL: 0,
                        },
                        RETURNED_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 0,
                            L: 0,
                            XL: 0,
                            XXL: 0,
                            XXXL: 0,
                        },
                        PRICE: 1599,
                        TOTAL: 7995,
                        PAID: 7995,
                        CREDIT: 0,
                        DEBIT: 7995,
                        BALANCE: 0,
                        ENTERPRISE_DETAILS: {
                            ENTERPRISE: 'Enterprise 1',
                            ADDRESS: 'Address 1',
                            CARD_NUMBER: 123456781234,
                            PHONE_NUMBER: 9876543211,
                            FAX: 'Fax 1',
                            EMAIL: 'Email 1',
                            WEBSITE: 'Website 1',
                            KGST: 'KGST 1',
                            TIN: 'TIN 1',
                            CST: 'CST 1',
                        }
                    },
                    {
                        ID: 'Item 1',
                        ITEM: 'Item 1',
                        QUANTITY: 5,
                        IS_STOCK_AVAILABLE: true,
                        TOTAL_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 10,
                            S: 10,
                            M: 20,
                            L: 10,
                            XL: 10,
                            XXL: 10,
                            XXXL: 10,
                        },
                        IN_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 2,
                            L: 0,
                            XL: 1,
                            XXL: 0,
                            XXXL: 0,
                        },
                        RETURNED_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 0,
                            L: 0,
                            XL: 0,
                            XXL: 0,
                            XXXL: 0,
                        },
                        PRICE: 1599,
                        TOTAL: 7995,
                        PAID: 7995,
                        CREDIT: 0,
                        DEBIT: 7995,
                        BALANCE: 0,
                        ENTERPRISE_DETAILS: {
                            ENTERPRISE: 'Enterprise 1',
                            ADDRESS: 'Address 1',
                            CARD_NUMBER: 123456781234,
                            PHONE_NUMBER: 9876543211,
                            FAX: 'Fax 1',
                            EMAIL: 'Email 1',
                            WEBSITE: 'Website 1',
                            KGST: 'KGST 1',
                            TIN: 'TIN 1',
                            CST: 'CST 1',
                        }
                    }

                ]
            }
        ]
    },
    {
        ID: 'Database 2',
        ALL_STOCK: [
            {
                ID: 'ASID 2',
                ENTERPRISE: 'Enterprise 2',
                ITEMS: [
                    {
                        ID: 'Item 2',
                        ITEM: 'Item 2',
                        QUANTITY: 5,
                        IS_STOCK_AVAILABLE: true,
                        TOTAL_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 10,
                            S: 10,
                            M: 20,
                            L: 10,
                            XL: 10,
                            XXL: 10,
                            XXXL: 10,
                        },
                        IN_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 2,
                            L: 0,
                            XL: 1,
                            XXL: 0,
                            XXXL: 0,
                        },
                        RETURNED_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 0,
                            L: 0,
                            XL: 0,
                            XXL: 0,
                            XXXL: 0,
                        },
                        PRICE: 1599,
                        TOTAL: 7995,
                        PAID: 7995,
                        CREDIT: 0,
                        DEBIT: 7995,
                        BALANCE: 0,
                        ENTERPRISE_DETAILS: {
                            ENTERPRISE: 'Enterprise 2',
                            ADDRESS: 'Address 2',
                            CARD_NUMBER: 123456781234,
                            PHONE_NUMBER: 9876543211,
                            FAX: 'Fax 2',
                            EMAIL: 'Email 2',
                            WEBSITE: 'Website 2',
                            KGST: 'KGST 2',
                            TIN: 'TIN 2',
                            CST: 'CST 2',
                        }
                    },
                    {
                        ID: 'Item 1',
                        ITEM: 'Item 1',
                        QUANTITY: 5,
                        IS_STOCK_AVAILABLE: true,
                        TOTAL_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 10,
                            S: 10,
                            M: 20,
                            L: 10,
                            XL: 10,
                            XXL: 10,
                            XXXL: 10,
                        },
                        IN_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 2,
                            L: 0,
                            XL: 1,
                            XXL: 0,
                            XXXL: 0,
                        },
                        RETURNED_STOCK_ITEMS: {
                            '28': 0,
                            '30': 0,
                            '32': 0,
                            '34': 0,
                            '36': 0,
                            '38': 0,
                            '40': 0,
                            '42': 0,
                            XS: 0,
                            S: 0,
                            M: 0,
                            L: 0,
                            XL: 0,
                            XXL: 0,
                            XXXL: 0,
                        },
                        PRICE: 1599,
                        TOTAL: 7995,
                        PAID: 7995,
                        CREDIT: 0,
                        DEBIT: 7995,
                        BALANCE: 0,
                        ENTERPRISE_DETAILS: {
                            ENTERPRISE: 'Enterprise 1',
                            ADDRESS: 'Address 1',
                            CARD_NUMBER: 123456781234,
                            PHONE_NUMBER: 9876543211,
                            FAX: 'Fax 1',
                            EMAIL: 'Email 1',
                            WEBSITE: 'Website 1',
                            KGST: 'KGST 1',
                            TIN: 'TIN 1',
                            CST: 'CST 1',
                        }
                    }
                ]
            }
        ]
    }
]