export default function PdfTable (){
    return(
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Enterprise</th>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Total</th>
                    <th>Credit</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>12/12/2021</td>
                    <td>Enterprise</td>
                    <td>Item</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Discount</td>
                    <td>Total</td>
                    <td>Credit</td>
                </tr>
                <tr>
                    <td>12/12/2021</td>
                    <td>Enterprise</td>
                    <td>Item</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Discount</td>
                    <td>Total</td>
                    <td>Credit</td>
                </tr>
                <tr>
                    <td>12/12/2021</td>
                    <td>Enterprise</td>
                    <td>Item</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Discount</td>
                    <td>Total</td>
                    <td>Credit</td>
                </tr>
                <tr>
                    <td>12/12/2021</td>
                    <td>Enterprise</td>
                    <td>Item</td>
                    <td>Quantity</td>
                    <td>Price</td>
                    <td>Discount</td>
                    <td>Total</td>
                    <td>Credit</td>
                </tr>
            </tbody>    
        </table>
    )
}